Resources:
  HelloLambdaServiceRoleE071F162:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkAppStack/HelloLambda/ServiceRole/Resource
  HelloLambda3D9C82D6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627S3BucketB7EFBFEA
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627S3VersionKey8FF4C7A4
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627S3VersionKey8FF4C7A4
      Role:
        Fn::GetAtt:
          - HelloLambdaServiceRoleE071F162
          - Arn
      Environment:
        Variables:
          isProduction: Not is not
      Handler: hello.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Timeout: 10
    DependsOn:
      - HelloLambdaServiceRoleE071F162
    Metadata:
      aws:cdk:path: CdkAppStack/HelloLambda/Resource
      aws:asset:path: /Users/malgorzatakrzek/cdk-app/lambda
      aws:asset:property: Code
  EndpointEEF1FD8F:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Endpoint
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Resource
  EndpointCloudWatchRoleC3C64E0F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/CloudWatchRole/Resource
  EndpointAccountB8304247:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - EndpointCloudWatchRoleC3C64E0F
          - Arn
    DependsOn:
      - EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Account
  EndpointDeployment318525DA68f253de9a992139ef5865adf6b78cb3:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      Description: Automatically created by the RestApi construct
    DependsOn:
      - EndpointproxyANYC09721C5
      - Endpointproxy39E2174E
      - EndpointANY485C938B
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Deployment/Resource
  EndpointDeploymentStageprodB78BEEA0:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: EndpointEEF1FD8F
      DeploymentId:
        Ref: EndpointDeployment318525DA68f253de9a992139ef5865adf6b78cb3
      StageName: prod
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/DeploymentStage.prod/Resource
  Endpointproxy39E2174E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: EndpointEEF1FD8F
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/{proxy+}/Resource
  EndpointproxyANYApiPermissionCdkAppStackEndpoint1AD78947ANYproxy51D04F69:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/*
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.CdkAppStackEndpoint1AD78947.ANY..{proxy+}
  EndpointproxyANYApiPermissionTestCdkAppStackEndpoint1AD78947ANYproxy4802EAF7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/{proxy+}/ANY/ApiPermission.Test.CdkAppStackEndpoint1AD78947.ANY..{proxy+}
  EndpointproxyANYC09721C5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: Endpointproxy39E2174E
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloLambda3D9C82D6
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/{proxy+}/ANY/Resource
  EndpointANYApiPermissionCdkAppStackEndpoint1AD78947ANYDDEECC4D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /
            - Ref: EndpointDeploymentStageprodB78BEEA0
            - /*/
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/ANY/ApiPermission.CdkAppStackEndpoint1AD78947.ANY..
  EndpointANYApiPermissionTestCdkAppStackEndpoint1AD78947ANY24949080:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloLambda3D9C82D6
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: EndpointEEF1FD8F
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/ANY/ApiPermission.Test.CdkAppStackEndpoint1AD78947.ANY..
  EndpointANY485C938B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - EndpointEEF1FD8F
          - RootResourceId
      RestApiId:
        Ref: EndpointEEF1FD8F
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloLambda3D9C82D6
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkAppStack/Endpoint/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE01P0U7DMAz8lr2n2cokeKUM8cREVb7ApF7J1iRV7DCqqP9OkzLok8+ns++ulOXuQe42j3ClQrWXbVTOo4zvDOoiKiLkGXbadqJBcsErFAdniX1QLA4nW4MHg4w+LW+Bh5Dpf/HJzvpWs3Z2Eskl9mA+WpDxJViV6KRZ4xq90UT5QIORsXF9fpTmJGhfQMpFMscTMOgOGK8wyviaX8/mXA36N8cNVkq5YFk849C70aDNQVdbKpp9FnCr8ASEovbue1yX+sNH5E/XJmpB0zQJ61qUZ9p+lXeyvJfl5kxaF3521wZls8wfrws7OHsBAAA=
    Metadata:
      aws:cdk:path: CdkAppStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627S3BucketB7EFBFEA:
    Type: String
    Description: S3 bucket for asset "e5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627"
  AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627S3VersionKey8FF4C7A4:
    Type: String
    Description: S3 key for asset version "e5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627"
  AssetParameterse5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627ArtifactHash98877790:
    Type: String
    Description: Artifact hash for asset "e5306d6740eefc1a5c00880e83644599e37de8be179fa6efcf30a17872e74627"
Outputs:
  Endpoint8024A810:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: EndpointEEF1FD8F
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: EndpointDeploymentStageprodB78BEEA0
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

